[
    {
        name:'abc',
        college:'abc'
    },
    {
        name:'def',
        college:'def'
    },
    {
        name:'asdsad',
        college:'asdsad'
    },
    {
        name:'asdasd',
        college:'sadsad'
    },
    {
        name:'rfafe',
        college:'rfafe'
    },
    {
        name:'ewrwfwef',
        college:'ewrwfwef'
    },
    {
        name:'hryneger',
        college:'hryneger'
    },
    {
        name:'qweeqw',
        college:'qweeqw'
    },
    {
        name:'bergwfefw',
        college:'efewfw'
    },
    {
        name:'rwgvr',
        college:'fwefwe'
    },
    {
        name:'vwrwfwf',
        college:'fwefwef'
    },
    {
        name:'reghthe',
        college:'grgrewgf'
    },
    {
        name:'grwgrwg',
        college:'wegwgfw'
    },
    {
        name:'wrgwrfw',
        college:'tehteh'
    },
    {
        name:'fwefewf',
        college:'fewfewf'
    },
    {
        name:'bebwbrr',
        college:'vwrwrv'
    },
    {
        name:'vregerf',
        college:'vcsdfwef'
    },
    {
        name:'rwsefg',
        college:'btehecwd'
    },
    {
        name:'ntejrth',
        college:'yjrthrt'
    },
    {
        name:'nrymryh',
        college:'bethtb'
    },
    {
        name:' jtyhrth',
        college:'vwrhrrthtmywrv'
    },
    {
        name:'ntyjyrj',
        college:'brthtr'
    }
]